"""Juan's judgements on plates, in a form Claude Code agents read and act on.

The viewer's old keep/rework/cut buttons wrote to ``localStorage`` — a store no
agent can see, so looking at 454 plates produced judgements that died in the
browser. This module is the on-disk half.

Two deliberate choices:

* Feedback lives under **tracked** ``studio/``, not under ``gallery/`` which is
  entirely gitignored. A note written into gallery/ would never version and
  would vanish on a clean checkout. ``STUDIO.md`` already declares that every
  piece's artifacts belong in ``studio/<slug>/``, which is also where an agent
  working on that piece looks.
* Every record carries the **piece path**. That is what makes feedback
  actionable rather than merely readable: a note on a render resolves to the
  source file an agent must edit.

Stdlib only, matching ``gallery_index.py`` — the project env does not reliably
resolve, so these tools must run from any interpreter.
"""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

REPO = Path(__file__).resolve().parent.parent
GALLERY = REPO / "gallery"
STUDIO = REPO / "studio"
LOG = STUDIO / "feedback.jsonl"

VERDICTS = ("promote", "rework", "cut")
# CURATION.md's vocabulary, so the two ledgers read alike.
CURATION_EQUIV = {"promote": "KEEP", "rework": "REWORK", "cut": "KILL"}

GENERATED = "Generated by `scripts/gallery_feedback.py` — do not edit by hand."

# gallery family -> studio slug, where the two names diverge
_ALIAS = {
    "massredist": "mass-redistribution",
    "res_backprop": "resonance-backprop",
    "res_ffn": "resonance-ffn",
    "ds_abacus": "double-slit",
    "ds_psy": "double-slit",
    "ds_lattice": "double-slit",
    "bacterio": "reaction-diffusion",
    "ssm_mamba": "ssm-mamba",
    "double_slit": "double-slit",
    "reaction_diffusion": "reaction-diffusion",
    "diffusion_topo": "diffusion-topography",
    "topo_scatter": "topography-scatter",
    "warped_grid": "warped-grid",
    "interf_annot": "interference-annotated",
    "gan_plate": "gan-plate",
    "attention_DAG": "attention-dag",
    "orbital_resonance": "orbital-resonance",
    "lstm_spirals": "lstm-spirals",
    "resonance_clean": "resonance-clean",
}


# Gallery subject -> the registered generator that draws it. These are NOT
# lexically derivable (neural-networks/mlp is drawn by `bauhaus_manifold`), so
# the mapping is stated rather than guessed. A subject in neither this table nor
# studio/ resolves to None, which the feedback file then says out loud.
_PACKAGE_PIECE = {
    "neural-networks/mlp": "bauhaus_manifold",
    "neural-networks/cnn": "bauhaus_locality",
    "neural-networks/lstm": "bauhaus_memory",
    "neural-networks/transformer/attention-topography": "bauhaus_relevance",
    "neural-networks/transformer/weights": "bauhaus_weights",
    "neural-networks/transformer/residual-stream": "residual_river",
    "neural-networks/transformer/positional-encoding": "pe_carpet",
    "neural-networks/perceptron": "bauhaus_loom",
    "neural-networks/decision-surface": "bauhaus_decision",
    "neural-networks/manifold": "bauhaus_manifold",
    "neural-networks/optimization/watershed": "bauhaus_gradient",
    "neural-networks/optimization/settling": "bauhaus_settling",
    "physics/black-hole/luminet": "black_hole",
    "physics/black-hole/bauhaus": "black_hole_bauhaus",
    "physics/warped-frame": "bauhaus_warped_frame",
    "physics/gravitational-waves": "gw150914",
    "physics/big-bang": "big_bang",
}


def _norm(x: str) -> str:
    return x.replace("-", "").replace("_", "").lower()


def slug_for(subject: str) -> str:
    """A filesystem-safe studio folder name for any gallery subject."""
    if subject.startswith("studio/"):
        fam = subject.split("/", 1)[1]
        fam = _ALIAS.get(fam, fam)
        # Gallery subjects are underscored (cnn_passes), studio families are
        # hyphenated (cnn-passes). Resolve against what is actually on disk
        # rather than guessing a convention, or feedback lands in a new empty
        # folder beside the real one and the agent never sees it.
        for cand in (fam, fam.replace("_", "-"), fam.replace("-", "_")):
            if (STUDIO / cand).is_dir():
                return cand
        return fam
    return subject.replace("/", "-")


def resolve_piece(subject: str) -> Optional[str]:
    """The source file an agent must edit to change this drawing.

    Returns a repo-relative path, or None when the drawing predates the studio
    and has no code on disk — recorded honestly rather than guessed at.
    """
    slug = slug_for(subject)
    rounds = STUDIO / slug / "rounds"
    if rounds.is_dir():
        # An approved snapshot wins; otherwise the newest round that has code.
        approved = sorted(rounds.glob("r*/*_APPROVED.py"))
        if approved:
            return str(approved[-1].relative_to(REPO))
        pieces = sorted(rounds.glob("r*/piece.py"))
        if pieces:
            return str(pieces[-1].relative_to(REPO))
    name = _PACKAGE_PIECE.get(subject)
    if not name:
        return None
    for rel in ("pieces/ml.py", "pieces/abstract.py", "pieces/physics.py", "generators.py"):
        src = REPO / "promptplot" / "generative" / rel
        if src.exists() and f"def {name}(" in src.read_text():
            return f"{src.relative_to(REPO)}::{name}"
    return None


def append(record: Dict[str, Any]) -> Dict[str, Any]:
    """Append one judgement. Append-only: the log is history, not a ledger."""
    verdict = str(record.get("verdict", "")).lower()
    if verdict not in VERDICTS:
        raise ValueError(f"verdict must be one of {VERDICTS}, got {verdict!r}")
    target = str(record.get("target", "")).strip("/")
    if not target or ".." in target:
        raise ValueError(f"bad target {target!r}")
    subject = record.get("subject") or "/".join(target.split("/")[:-2])
    entry = {
        "when": datetime.now().isoformat(timespec="seconds"),
        "target": target,
        "subject": subject,
        "verdict": verdict,
        "note": (record.get("note") or "").strip(),
        "refs": [r.strip("@ ") for r in (record.get("refs") or []) if r.strip()],
        "piece": resolve_piece(subject),
        "applied": False,
    }
    STUDIO.mkdir(parents=True, exist_ok=True)
    with LOG.open("a") as fh:
        fh.write(json.dumps(entry) + "\n")
    return entry


def load() -> List[Dict[str, Any]]:
    """Every record. A corrupt line is skipped, never fatal."""
    if not LOG.exists():
        return []
    out = []
    for line in LOG.read_text().splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            out.append(json.loads(line))
        except (json.JSONDecodeError, ValueError):
            continue
    return out


def latest_by_target(records: Optional[List[Dict]] = None) -> Dict[str, Dict]:
    """Newest judgement per plate — the log is append-only, so last wins."""
    out: Dict[str, Dict] = {}
    for r in records if records is not None else load():
        out[r["target"]] = r
    return out


def _fmt_refs(refs: List[str]) -> str:
    return " ".join(f"`gallery/{r}`" for r in refs) if refs else "—"


def write_views() -> Dict[str, int]:
    """Regenerate the three markdown files agents actually read."""
    records = load()
    current = latest_by_target(records)
    by_subject: Dict[str, List[Dict]] = {}
    for r in current.values():
        by_subject.setdefault(r["subject"], []).append(r)

    # 1. per-drawing, beside the piece — what an agent reads before working
    for subject, rs in by_subject.items():
        slug = slug_for(subject)
        d = STUDIO / slug
        d.mkdir(parents=True, exist_ok=True)
        piece = rs[0].get("piece")
        lines = [
            f"# Feedback — {subject}",
            "",
            GENERATED,
            "",
            "**Read this before changing this drawing.** Each entry is Juan's judgement on a "
            "specific render. PROMOTE = keep as the final. REWORK = good bones, fix what the "
            "note says. CUT = drop it.",
            "",
            f"**Source:** `{piece}`" if piece else
            "**Source:** not on disk — this drawing predates the studio and cannot be regenerated.",
            "",
        ]
        for r in sorted(rs, key=lambda x: x["when"], reverse=True):
            lines += [
                f"## {r['verdict'].upper()} — `{r['target'].rsplit('/', 1)[-1]}`",
                "",
                f"- **when** {r['when']}",
                f"- **plate** `gallery/{r['target']}`",
                f"- **see also** {_fmt_refs(r['refs'])}",
                "",
                r["note"] or "_no note_",
                "",
            ]
        (d / "FEEDBACK.md").write_text("\n".join(lines) + "\n")

    # 2. the roll-up, in CURATION.md's own column shape
    roll = [
        "# Feedback ledger",
        "",
        GENERATED,
        "",
        "Juan's verdicts from the gallery viewer. Vocabulary maps to "
        "`promptplot/generative/CURATION.md`: PROMOTE = KEEP, REWORK = REWORK, CUT = KILL.",
        "",
        "| Plate | Verdict | Note | See also |",
        "|---|---|---|---|",
    ]
    for r in sorted(current.values(), key=lambda x: (x["subject"], x["when"])):
        note = (r["note"] or "—").replace("|", "\\|").replace("\n", " ")
        roll.append(
            f"| `{r['subject']}` / {r['target'].rsplit('/', 1)[-1]} "
            f"| **{r['verdict'].upper()}** | {note} | {_fmt_refs(r['refs'])} |"
        )
    (STUDIO / "FEEDBACK.md").write_text("\n".join(roll) + "\n")

    # 3. the worklist — open reworks, what agents get dispatched against
    todo = [r for r in current.values() if r["verdict"] == "rework" and not r.get("applied")]
    q = [
        "# Queue",
        "",
        GENERATED,
        "",
        f"{len(todo)} drawing(s) awaiting rework. Each line names the plate, the source to "
        "edit, and what Juan asked for.",
        "",
    ]
    for r in sorted(todo, key=lambda x: x["when"]):
        q += [
            f"- [ ] **{r['subject']}** — `gallery/{r['target']}`",
            f"      source: `{r['piece'] or 'none on disk'}`",
            f"      {r['note'] or '_no note_'}",
        ]
        if r["refs"]:
            q.append(f"      see also: {_fmt_refs(r['refs'])}")
    (STUDIO / "QUEUE.md").write_text("\n".join(q) + "\n")

    return {"records": len(records), "plates": len(current),
            "subjects": len(by_subject), "queued": len(todo)}


if __name__ == "__main__":
    import sys

    if len(sys.argv) > 1 and sys.argv[1] == "--rebuild":
        print(write_views())
    else:
        for r in load():
            print(f"{r['when']}  {r['verdict']:8} {r['target']}")
