"""Juan's judgements on plates, in a form Claude Code agents read and act on.

The viewer's old keep/rework/cut buttons wrote to ``localStorage`` — a store no
agent can see, so looking at 454 plates produced judgements that died in the
browser. This module is the on-disk half.

Two deliberate choices:

* Feedback lives under **tracked** ``studio/``, not under ``gallery/`` which is
  entirely gitignored. A note written into gallery/ would never version and
  would vanish on a clean checkout. ``STUDIO.md`` already declares that every
  piece's artifacts belong in ``studio/<slug>/``, which is also where an agent
  working on that piece looks.
* Every record carries the **piece path**. That is what makes feedback
  actionable rather than merely readable: a note on a render resolves to the
  source file an agent must edit.

Stdlib only, matching ``gallery_index.py`` — the project env does not reliably
resolve, so these tools must run from any interpreter.
"""

from __future__ import annotations

import json
import logging
import re
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

logger = logging.getLogger(__name__)

REPO = Path(__file__).resolve().parent.parent
GALLERY = REPO / "gallery"
STUDIO = REPO / "studio"
LOG = STUDIO / "feedback.jsonl"

# Render verdicts judge one file; direction verdicts judge the approach behind a
# family of renders (see gallery_directions.py) and steer future studio runs.
RENDER_VERDICTS = ("promote", "keep", "rework", "archive", "cut")
DIRECTION_VERDICTS = ("works", "maybe", "dead_end")
# Publish verdicts pick the plates that go to Juan's portfolio site (read by the
# site exporter through latest_published). They never move a file.
PUBLISH_VERDICTS = ("publish", "unpublish")
VERDICTS = RENDER_VERDICTS + DIRECTION_VERDICTS + PUBLISH_VERDICTS  # every verdict the log may hold
SCOPES = {"render": RENDER_VERDICTS, "direction": DIRECTION_VERDICTS,
          "publish": PUBLISH_VERDICTS}
PUBLISH_EXT = (".png", ".jpg", ".jpeg", ".webp")
# CURATION.md's vocabulary, so the two ledgers read alike. KEEP here is a
# *flavour worth keeping*; CURATION.md's KEEP (the final) is PROMOTE.
CURATION_EQUIV = {"promote": "KEEP", "keep": "FLAVOUR", "rework": "REWORK",
                  "archive": "PARKED", "cut": "KILL"}
DIRECTION_KEY = re.compile(r"(r\d{2,3}|original|x-[a-z0-9-]{1,40})")

GENERATED = "Generated by `scripts/gallery_feedback.py` — do not edit by hand."

# gallery family -> studio slug, where the two names diverge
_ALIAS = {
    "massredist": "mass-redistribution",
    "res_backprop": "resonance-backprop",
    "res_ffn": "resonance-ffn",
    "ds_abacus": "double-slit",
    "ds_psy": "double-slit",
    "ds_lattice": "double-slit",
    "bacterio": "reaction-diffusion",
    "ssm_mamba": "ssm-mamba",
    "double_slit": "double-slit",
    "reaction_diffusion": "reaction-diffusion",
    "diffusion_topo": "diffusion-topography",
    "topo_scatter": "topography-scatter",
    "warped_grid": "warped-grid",
    "interf_annot": "interference-annotated",
    "gan_plate": "gan-plate",
    "attention_DAG": "attention-dag",
    "orbital_resonance": "orbital-resonance",
    "lstm_spirals": "lstm-spirals",
    "resonance_clean": "resonance-clean",
}


# Gallery subject -> the registered generator that draws it. These are NOT
# lexically derivable (neural-networks/mlp is drawn by `bauhaus_manifold`), so
# the mapping is stated rather than guessed. A subject in neither this table nor
# studio/ resolves to None, which the feedback file then says out loud.
_PACKAGE_PIECE = {
    "neural-networks/mlp": "bauhaus_manifold",
    "neural-networks/cnn": "bauhaus_locality",
    "neural-networks/lstm": "bauhaus_memory",
    "neural-networks/transformer/attention-topography": "bauhaus_relevance",
    "neural-networks/transformer/weights": "bauhaus_weights",
    "neural-networks/transformer/residual-stream": "residual_river",
    "neural-networks/transformer/positional-encoding": "pe_carpet",
    "neural-networks/perceptron": "bauhaus_loom",
    "neural-networks/decision-surface": "bauhaus_decision",
    "neural-networks/manifold": "bauhaus_manifold",
    "neural-networks/optimization/watershed": "bauhaus_gradient",
    "neural-networks/optimization/settling": "bauhaus_settling",
    "physics/black-hole/luminet": "black_hole",
    "physics/black-hole/bauhaus": "black_hole_bauhaus",
    "physics/warped-frame": "bauhaus_warped_frame",
    "physics/gravitational-waves": "gw150914",
    "physics/big-bang": "big_bang",
}


def _norm(x: str) -> str:
    return x.replace("-", "").replace("_", "").lower()


def slug_for(subject: str) -> str:
    """A filesystem-safe studio folder name for any gallery subject."""
    if subject.startswith("studio/"):
        fam = subject.split("/", 1)[1]
        fam = _ALIAS.get(fam, fam)
        # Gallery subjects are underscored (cnn_passes), studio families are
        # hyphenated (cnn-passes). Resolve against what is actually on disk
        # rather than guessing a convention, or feedback lands in a new empty
        # folder beside the real one and the agent never sees it.
        for cand in (fam, fam.replace("_", "-"), fam.replace("-", "_")):
            if (STUDIO / cand).is_dir():
                return cand
        return fam
    return subject.replace("/", "-")


def resolve_piece(subject: str) -> Optional[str]:
    """The source file an agent must edit to change this drawing.

    Returns a repo-relative path, or None when the drawing predates the studio
    and has no code on disk — recorded honestly rather than guessed at.
    """
    slug = slug_for(subject)
    rounds = STUDIO / slug / "rounds"
    if rounds.is_dir():
        # An approved snapshot wins; otherwise the newest round that has code.
        approved = sorted(rounds.glob("r*/*_APPROVED.py"))
        if approved:
            return str(approved[-1].relative_to(REPO))
        pieces = sorted(rounds.glob("r*/piece.py"))
        if pieces:
            return str(pieces[-1].relative_to(REPO))
    name = _PACKAGE_PIECE.get(subject)
    if not name:
        return None
    for rel in ("pieces/ml.py", "pieces/abstract.py", "pieces/physics.py", "generators.py"):
        src = REPO / "promptplot" / "generative" / rel
        if src.exists() and f"def {name}(" in src.read_text():
            return f"{src.relative_to(REPO)}::{name}"
    return None


def append(record: Dict[str, Any]) -> Dict[str, Any]:
    """Append one judgement. Append-only: the log is history, not a ledger.

    ``scope`` is ``render`` (default — every pre-scope record is one),
    ``direction`` or ``publish``. A direction record's target is the virtual path
    ``<subject>/@direction/<key>`` and a publish record's is
    ``<subject>/@publish/<basename>`` — inside gallery/, never a file — so
    ``latest_by_target`` keeps the kinds apart with no schema change.
    """
    scope = str(record.get("scope") or "render").lower()
    if scope not in SCOPES:
        raise ValueError(f"scope must be one of {tuple(SCOPES)}, got {scope!r}")
    verdict = str(record.get("verdict", "")).lower()
    if verdict not in SCOPES[scope]:
        raise ValueError(f"{scope} verdict must be one of {SCOPES[scope]}, got {verdict!r}")
    target = str(record.get("target", "")).strip("/")
    if not target or ".." in target:
        raise ValueError(f"bad target {target!r}")
    extra: Dict[str, Any] = {}
    if scope == "render":
        if any(seg.startswith("@") for seg in target.split("/")):
            raise ValueError(f"a render target cannot contain an @ segment: {target!r}")
        subject = record.get("subject") or "/".join(target.split("/")[:-2])
    elif scope == "publish":
        subject = str(record.get("subject") or "").strip("/")
        basename = str(record.get("basename") or "")
        if not subject or ".." in subject or "@" in subject:
            raise ValueError(f"a publish record needs a plain subject, got {subject!r}")
        if not basename or "/" in basename or not basename.lower().endswith(PUBLISH_EXT):
            raise ValueError(f"publish basename must be an image file name {PUBLISH_EXT}, "
                             f"got {basename!r}")
        if target != f"{subject}/@publish/{basename}":
            raise ValueError(f"publish target must be {subject}/@publish/{basename}, got {target!r}")
        extra = {"basename": basename}
    else:
        subject = str(record.get("subject") or "").strip("/")
        key = str(record.get("direction") or "")
        if not subject or ".." in subject or "@" in subject:
            raise ValueError(f"a direction record needs a plain subject, got {subject!r}")
        if not DIRECTION_KEY.fullmatch(key):
            raise ValueError(f"bad direction key {key!r}")
        if target != f"{subject}/@direction/{key}":
            raise ValueError(f"direction target must be {subject}/@direction/{key}, got {target!r}")
        extra = {"direction": key,
                 "label": str(record.get("label") or "").strip(),
                 "root": str(record.get("root") or "").strip() or None}
    entry = {
        "when": datetime.now().isoformat(timespec="seconds"),
        "scope": scope,
        "target": target,
        "subject": subject,
        "verdict": verdict,
        **extra,
        "note": (record.get("note") or "").strip(),
        "refs": [r.strip("@ ") for r in (record.get("refs") or []) if str(r).strip()],
        "piece": resolve_piece(subject),
        "applied": False,
    }
    STUDIO.mkdir(parents=True, exist_ok=True)
    with LOG.open("a") as fh:
        fh.write(json.dumps(entry) + "\n")
    return entry


def scope_of(rec: Dict[str, Any]) -> str:
    """Old records carry no scope: they are all render verdicts."""
    return rec.get("scope") or "render"


def load() -> List[Dict[str, Any]]:
    """Every record. A corrupt line is skipped, never fatal."""
    if not LOG.exists():
        return []
    out = []
    for line in LOG.read_text().splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            out.append(json.loads(line))
        except (json.JSONDecodeError, ValueError):
            continue
    return out


def latest_by_target(records: Optional[List[Dict]] = None) -> Dict[str, Dict]:
    """Newest judgement per plate — the log is append-only, so last wins."""
    out: Dict[str, Dict] = {}
    for r in records if records is not None else load():
        out[r["target"]] = r
    return out


def latest_by_render(records: Optional[List[Dict]] = None) -> Dict[Tuple[str, str], Dict]:
    """Newest render verdict per (subject, basename) — survives a tier move."""
    out: Dict[Tuple[str, str], Dict] = {}
    for r in records if records is not None else load():
        if scope_of(r) == "render":
            out[(r["subject"], r["target"].rsplit("/", 1)[-1])] = r
    return out


def latest_directions(records: Optional[List[Dict]] = None) -> Dict[Tuple[str, str], Dict]:
    """Newest direction verdict per (studio slug, direction key)."""
    out: Dict[Tuple[str, str], Dict] = {}
    for r in records if records is not None else load():
        if scope_of(r) == "direction" and r.get("direction"):
            out[(slug_for(r["subject"]), r["direction"])] = r
    return out


def latest_published(records: Optional[List[Dict]] = None) -> Dict[Tuple[str, str], Dict]:
    """Plates currently published to the site: (subject, basename) -> newest record.

    The newest publish-scope record per plate decides, so an ``unpublish``
    after a ``publish`` removes the plate. Render verdicts on the same file
    never touch it.
    """
    out: Dict[Tuple[str, str], Dict] = {}
    for r in records if records is not None else load():
        if scope_of(r) == "publish" and r.get("basename"):
            out[(r["subject"], r["basename"])] = r
    return {k: r for k, r in out.items() if r["verdict"] == "publish"}


def _fmt_refs(refs: List[str]) -> str:
    return " ".join(f"`gallery/{r}`" for r in refs) if refs else "—"


def _cell(x: Any) -> str:
    return (str(x) if x else "—").replace("|", "\\|").replace("\n", " ")


def _gd():
    """gallery_directions, imported lazily (it imports this module lazily too)."""
    import sys

    here = str(Path(__file__).resolve().parent)
    if here not in sys.path:
        sys.path.insert(0, here)
    import gallery_directions

    return gallery_directions


def _plate_directions(slug: str) -> Dict[str, Dict[str, Any]]:
    try:
        return _gd().directions_for_slug(slug)
    except Exception:  # a malformed ledger must never block saving a verdict
        logger.exception("directions unreadable for %s", slug)
        return {}


def steering(slug: str, records: Optional[List[Dict]] = None) -> Dict[str, Any]:
    """What Juan's verdicts say a studio run on ``slug`` must do.

    -> {"directions": {works|maybe|dead_end: [{key, label, rounds, note}]},
        "avoid_parents": rounds never to fork from (dead-end directions, and
                         rounds whose ledger render was ARCHIVEd or CUT),
        "protected": KEEP render basenames (flavours to leave alone),
        "verdicts": {direction key: verdict}}
    """
    records = load() if records is None else records
    dirs = _plate_directions(slug)
    out: Dict[str, Any] = {"directions": {v: [] for v in DIRECTION_VERDICTS},
                           "avoid_parents": [], "protected": [], "verdicts": {}}
    avoid: set = set()
    for (s, key), rec in sorted(latest_directions(records).items()):
        if s != slug:
            continue
        d = dirs.get(key, {})
        out["verdicts"][key] = rec["verdict"]
        out["directions"][rec["verdict"]].append({
            "key": key, "label": d.get("label") or rec.get("label") or key,
            "rounds": list(d.get("rounds", [])), "note": rec.get("note", "")})
        if rec["verdict"] == "dead_end":
            avoid.update(d.get("rounds", []))
    parked: set = set()
    for (subject, name), rec in latest_by_render(records).items():
        if slug_for(subject) != slug:
            continue
        if rec["verdict"] in ("archive", "cut"):
            parked.add(Path(name).stem)
        elif rec["verdict"] == "keep":
            out["protected"].append(name)
    if parked:
        try:
            rows = _gd().ledger(slug)
        except Exception:
            logger.exception("ledger unreadable for %s", slug)
            rows = []
        avoid.update(r["round"] for r in rows if r["render"] and Path(r["render"]).stem in parked)
    out["avoid_parents"] = sorted(avoid, key=lambda r: int(r[1:]) if r[1:].isdigit() else 0)
    out["protected"].sort()
    return out


_VERDICT_ORDER = {v: i for i, v in enumerate(DIRECTION_VERDICTS)}


def _directions_block(slug: str, dirs: Dict[str, Dict], recs: Dict[str, Dict],
                      avoid: List[str]) -> List[str]:
    lines = [
        "## Directions",
        "",
        "Juan's verdict on each APPROACH (a ledger root and every round that continued it). "
        "WORKS = continue it; MAYBE = open; DEAD END = never re-propose it or fork from it.",
        "",
        "| Verdict | Key | Label | Rounds | Canon / order / lineage | Note |",
        "|---|---|---|---|---|---|",
    ]
    keys = list(dirs) + [k for k in recs if k not in dirs]
    for key in keys:
        d, rec = dirs.get(key, {}), recs.get(key, {})
        verdict = rec.get("verdict", "")
        col = " / ".join(x for x in (d.get("canon", ""), d.get("order", ""), d.get("lineage", "")) if x)
        lines.append(
            f"| {('**' + verdict.upper().replace('_', ' ') + '**') if verdict else 'unjudged'} "
            f"| `{key}` | {_cell(d.get('label') or rec.get('label'))} "
            f"| {_cell(', '.join(d.get('rounds', [])))} | {_cell(col)} | {_cell(rec.get('note'))} |")
    if not keys:
        lines = lines[:-2] + ["_No directions yet — this plate has no studio ledger and no "
                              "direction verdicts._"]
    lines += ["", f"**Rounds not to fork from:** {', '.join(avoid) if avoid else 'none'}", ""]
    return lines


def write_views() -> Dict[str, int]:
    """Regenerate the markdown files agents actually read.

    studio/<slug>/FEEDBACK.md (Directions table first, then every render verdict),
    studio/FEEDBACK.md (roll-up), studio/DIRECTIONS.md (collection-wide direction
    verdicts) and studio/QUEUE.md (open reworks only).
    """
    records = load()
    current = latest_by_target(records)
    renders = {t: r for t, r in current.items() if scope_of(r) == "render"}
    dir_recs = latest_directions(records)

    by_slug: Dict[str, Dict[str, Any]] = {}
    for r in current.values():
        # A publish verdict says nothing to an agent working on the piece: a
        # publish-only plate must not get a FEEDBACK.md stub of its own.
        if scope_of(r) not in ("render", "direction"):
            continue
        g = by_slug.setdefault(slug_for(r["subject"]),
                               {"subjects": [], "renders": [], "dirs": {}, "piece": None})
        if r["subject"] not in g["subjects"]:
            g["subjects"].append(r["subject"])
        g["piece"] = g["piece"] or r.get("piece")
        if scope_of(r) == "render":
            g["renders"].append(r)
    for (slug, key), r in dir_recs.items():
        by_slug.setdefault(slug, {"subjects": [r["subject"]], "renders": [], "dirs": {},
                                  "piece": r.get("piece")})["dirs"][key] = r

    plate_dirs: Dict[str, Dict[str, Dict]] = {}
    # 1. per-drawing, beside the piece — what an agent reads before working
    for slug, g in by_slug.items():
        d = STUDIO / slug
        d.mkdir(parents=True, exist_ok=True)
        dirs = plate_dirs[slug] = _plate_directions(slug)
        steer = steering(slug, records)
        piece = g["piece"]
        lines = [
            f"# Feedback — {', '.join(g['subjects'])}",
            "",
            GENERATED,
            "",
            "**Read this before changing this drawing.**",
            "",
            f"**Source:** `{piece}`" if piece else
            "**Source:** not on disk — this drawing predates the studio and cannot be regenerated.",
            "",
        ]
        lines += _directions_block(slug, dirs, g["dirs"], steer["avoid_parents"])
        lines += [
            "## Renders",
            "",
            "Each entry is Juan's judgement on one specific render. "
            "PROMOTE = the final version of this drawing. "
            "KEEP = a flavour worth keeping — protected, do not rework or delete it "
            "(this is NOT CURATION.md's KEEP; that one is PROMOTE). "
            "REWORK = good bones, fix what the note says. "
            "ARCHIVE = not now — parked in `archive/`, recoverable, never a parent. "
            "CUT = drop it — moved to `cut/`, never deleted, never a parent.",
            "",
        ]
        for r in sorted(g["renders"], key=lambda x: x["when"], reverse=True):
            lines += [
                f"### {r['verdict'].upper()} — `{r['target'].rsplit('/', 1)[-1]}`",
                "",
                f"- **when** {r['when']}",
                f"- **plate** `gallery/{r['target']}`",
                f"- **see also** {_fmt_refs(r.get('refs') or [])}",
                "",
                r.get("note") or "_no note_",
                "",
            ]
        if not g["renders"]:
            lines += ["_no render verdicts yet_", ""]
        (d / "FEEDBACK.md").write_text("\n".join(lines) + "\n")

    # 2. the roll-up, in CURATION.md's own column shape
    roll = [
        "# Feedback ledger",
        "",
        GENERATED,
        "",
        "Juan's verdicts from the gallery viewer. Vocabulary maps to "
        "`promptplot/generative/CURATION.md`: PROMOTE = KEEP, KEEP = a flavour worth keeping "
        "(FLAVOUR — not CURATION's KEEP), REWORK = REWORK, ARCHIVE = PARKED, CUT = KILL.",
        "",
        "| Plate | Verdict | Note | See also |",
        "|---|---|---|---|",
    ]
    for r in sorted(renders.values(), key=lambda x: (x["subject"], x["when"])):
        roll.append(
            f"| `{r['subject']}` / {r['target'].rsplit('/', 1)[-1]} "
            f"| **{r['verdict'].upper()}** | {_cell(r.get('note'))} | {_fmt_refs(r.get('refs') or [])} |"
        )
    roll += [
        "",
        "## Directions",
        "",
        "WORKS = continue it · MAYBE = open · DEAD END = never re-propose. "
        "Full table in `studio/DIRECTIONS.md`.",
        "",
        "| Plate | Direction | Label | Verdict | Note |",
        "|---|---|---|---|---|",
    ]
    ordered = sorted(dir_recs.items(),
                     key=lambda kv: (kv[0][0], _VERDICT_ORDER.get(kv[1]["verdict"], 9), kv[0][1]))
    for (slug, key), r in ordered:
        label = plate_dirs.get(slug, {}).get(key, {}).get("label") or r.get("label")
        roll.append(f"| `{slug}` | `{key}` | {_cell(label)} "
                    f"| **{r['verdict'].upper().replace('_', ' ')}** | {_cell(r.get('note'))} |")
    (STUDIO / "FEEDBACK.md").write_text("\n".join(roll) + "\n")

    # 3. the collection's directions — what the studio lead reads to steer a run
    dl = [
        "# Directions",
        "",
        GENERATED,
        "",
        "Juan's verdicts on the APPROACHES behind the renders, across every plate. "
        "A studio run continues WORKS directions and never re-proposes a DEAD END "
        "(nor forks from any of its rounds).",
        "",
        "| Verdict | Plate | Direction | Label | Canon | Order | Lineage | Note |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for (slug, key), r in sorted(dir_recs.items(),
                                 key=lambda kv: (_VERDICT_ORDER.get(kv[1]["verdict"], 9), kv[0])):
        d = plate_dirs.get(slug, {}).get(key, {})
        dl.append(
            f"| **{r['verdict'].upper().replace('_', ' ')}** | `{slug}` | `{key}` "
            f"| {_cell(d.get('label') or r.get('label'))} | {_cell(d.get('canon'))} "
            f"| {_cell(d.get('order'))} | {_cell(d.get('lineage'))} | {_cell(r.get('note'))} |")
    if not dir_recs:
        dl += ["", "_No direction verdicts yet — judge them with W / M / D in the viewer._"]
    (STUDIO / "DIRECTIONS.md").write_text("\n".join(dl) + "\n")

    # 4. the worklist — open reworks, what agents get dispatched against
    todo = [r for r in renders.values() if r["verdict"] == "rework" and not r.get("applied")]
    q = [
        "# Queue",
        "",
        GENERATED,
        "",
        f"{len(todo)} drawing(s) awaiting rework. Each line names the plate, the source to "
        "edit, and what Juan asked for.",
        "",
    ]
    for r in sorted(todo, key=lambda x: x["when"]):
        q += [
            f"- [ ] **{r['subject']}** — `gallery/{r['target']}`",
            f"      source: `{r.get('piece') or 'none on disk'}`",
            f"      {r.get('note') or '_no note_'}",
        ]
        if r.get("refs"):
            q.append(f"      see also: {_fmt_refs(r['refs'])}")
    (STUDIO / "QUEUE.md").write_text("\n".join(q) + "\n")

    return {"records": len(records), "plates": len(renders),
            "subjects": len(by_slug), "queued": len(todo), "directions": len(dir_recs)}


if __name__ == "__main__":
    import sys

    if len(sys.argv) > 1 and sys.argv[1] == "--rebuild":
        print(write_views())
    else:
        for r in load():
            print(f"{r['when']}  {scope_of(r):9} {r['verdict']:8} {r['target']}")
