"""Rebuild studio/DESCRIPTIONS.md — one row per plate from every studio/<slug>/DESCRIPTION.md.

A DESCRIPTION.md is the vision-reviewed spec of a plate's current version (what is on
the sheet, what to keep, what is weak, candidate next theses). This index is what a
studio workflow reads to choose which plates to iterate and with which theses:

    python scripts/studio_descriptions.py            # rewrite the index
    python scripts/studio_descriptions.py --json     # print rows as JSON (workflow args)
"""

from __future__ import annotations

import argparse
import json
import logging
import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
STUDIO = REPO / "studio"
OUT = STUDIO / "DESCRIPTIONS.md"

logger = logging.getLogger(__name__)

_ROW = re.compile(r"^\|\s*([^|]+?)\s*\|\s*(.+?)\s*\|\s*$")
_SRC = re.compile(r"(studio/[\w\-/.]+/piece\w*\.py(?:::\w+)?|promptplot/generative/[\w\-/.]+\.py::\w+)")
_THESIS = re.compile(r"^\s*(?:[-*]|\d+\.)?\s*\*\*([^*]+?)\*\*\s*\(([^)]*)\)")


def _section(text: str, heading: str) -> str:
    m = re.search(rf"^## {re.escape(heading)}[^\n]*\n(.*?)(?=^## |\Z)", text, re.M | re.S)
    return m.group(1).strip() if m else ""


def parse(path: Path) -> dict:
    text = path.read_text()
    title = re.search(r"^# (.+?)(?: — description)?\s*$", text, re.M)
    table = {}
    for line in text.splitlines():
        m = _ROW.match(line)
        if m and not set(m.group(1)) <= {"-", " "} and m.group(1).strip():
            table.setdefault(m.group(1).strip().lower(), m.group(2).strip())
    theses = []
    for line in _section(text, "Next versions").splitlines():
        m = _THESIS.match(line)
        if m and not m.group(1).lower().startswith("if only"):
            theses.append({"name": m.group(1).strip(), "kind": m.group(2).strip()})
    one_line = " ".join(_section(text, "In one line").split())
    source = table.get("source", "").replace("`", "")
    rounds = sorted(int(d.name[1:]) for d in (path.parent / "rounds").glob("r[0-9]*") if d.name[1:].isdigit())
    path_m = _SRC.search(source)
    parent = None
    if path_m:
        parent = path_m.group(1)
        own = re.match(rf"studio/{re.escape(path.parent.name)}/rounds/(r\d+)/", parent)
        parent = own.group(1) if own else parent
    return {
        "slug": path.parent.name,
        "title": title.group(1).strip() if title else path.parent.name,
        "one_line": one_line,
        "status": table.get("status", ""),
        "source": source,
        "parent": parent,
        "next_round": (rounds[-1] + 1) if rounds else 1,
        "current": table.get("current render", ""),
        "theses": theses,
        "path": str(path.relative_to(REPO)),
    }


def rows() -> list[dict]:
    return [parse(p) for p in sorted(STUDIO.glob("*/DESCRIPTION.md"))]


def _short(status: str) -> str:
    return status.replace("*", "").split("·")[0].split("(")[0].strip() or "—"


def render(items: list[dict]) -> str:
    lines = [
        "# Studio descriptions",
        "",
        "Generated by `scripts/studio_descriptions.py` — do not edit by hand; edit the",
        "per-plate `studio/<slug>/DESCRIPTION.md` and re-run.",
        "",
        f"{len(items)} plates. Each DESCRIPTION.md is the starting spec a studio round iterates from.",
        "",
        "| plate | in one line | status | next theses |",
        "|---|---|---|---|",
    ]
    for r in items:
        theses = " · ".join(f"`{t['name']}` ({t['kind']})" for t in r["theses"]) or "—"
        one = r["one_line"].replace("|", "/")
        lines.append(f"| [{r['title']}]({r['slug']}/DESCRIPTION.md) `{r['slug']}` | {one} | {_short(r['status'])} | {theses} |")
    return "\n".join(lines) + "\n"


def main() -> None:
    logging.basicConfig(format="%(asctime)s %(name)s %(levelname)s %(message)s", level=logging.INFO)
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--json", action="store_true", help="print the rows as JSON instead of writing the index")
    args = ap.parse_args()
    items = rows()
    if args.json:
        print(json.dumps(items, indent=1, ensure_ascii=False))
        return
    OUT.write_text(render(items))
    logger.info("%d plates -> %s", len(items), OUT.relative_to(REPO))


if __name__ == "__main__":
    main()
